-- init doc key
-- A = Air : eə
-- B = Bat : bæt
-- C = Cap : kæp
-- D = Drum	: drʌm
-- E = Each	: iːtʃ
-- F = Fine : faɪn
-- G = Gust	: ɡʌst
-- H = Harp	: hɑːp
-- I = Sit	: sɪt
-- J = Jury	: dʒʊəri
-- K = Krunch : krʌntʃ
-- L = Look : lʊk
-- M = Made	: meɪd
-- N = Near	: nɪər
-- O = Odd	: ɒd
-- P = Pit	: pɪt
-- Q = Quench	
-- R = Red
-- S = Sun	
-- T = Trap
-- U = Urge
-- V = Vest
-- W = Whale
-- X = Plex
-- Y = Yank	
-- Z = Zip	
-- Ctrl = Control	
-- Shift = Shift	
-- Esc = Escape	
-- spacebar = Space
-- Tab = Tab
-- Enter = Enter
-- ` = back tick
-- - = dash
-- ? = question mark
-- , = comma
-- . = dot
-- ' = quote
-- () = left paren and right paren
-- [] = left square bracket and right square
-- {} = left brace and right brace
-- <> = left angle and right angle
-- : being colon and
-- ; being semicolon
-- ! is bang
-- = equals
-- _ down score
-- - minus
-- + plus
-- * star
-- # hash
-- / slash
-- \ back slash
-- $ dollar
-- % percent
-- ^ caret
-- & and sign
-- | pipe
-- @ at sign
-- ~ tilde : ˈtɪldə
-- backspace = wipe
-- end doc key
--
--
-- https://github.com/talonhub/community/blob/main/core/keys/keys.py#L176
