-- Doc most used keymaps for vim (only standard keymaps)
-- init doc key
-- {'n'} ggVG = select all
-- {'n'} <C-r> = redo
-- {'n'} <S-p> = paste
-- {'n'} y = copy
-- {'n'} d = cut
-- {'n'} F = find in line backward
-- {'n'} f = find in line forward
-- {'n'} <C-d> = move cursor down page
-- {'n'} <C-u> = move cursor up page
-- {'n'} K = move cursor to below line
-- {'n'} J = move cursor to above line
-- {'v'} K = move selected line / block of text up
-- {'v'} J = move selected line / block of text down
-- end doc key
