# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0babf77e-9d94-4286-b5bb-e6ba16f37288";
      fsType = "ext4";
      options = [ "noatime" ];
    };


  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6AD8-50AC";
      fsType = "vfat";
    };

  
  swapDevices = [{
    device = "/var/lib/swapfile";
    size = 4*1024;
  }];
  
  security.protectKernelImage = false; 
  # sudo filefrag -v /var/lib/swapfile | awk '$1=="0:" {print substr($4, 1, length($4)-2)}'
  # To get the resume_offset  
  boot.kernelParams = [  "resume=/var/lib/swapfile" "resume_offset=122290176" "kvm.enable_virt_at_load=0" ];
  boot.resumeDevice = "/dev/disk/by-uuid/0babf77e-9d94-4286-b5bb-e6ba16f37288";


  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
